Eligible couple tracking bugs done
PSMRI/FLW-Mobile-App pull request #4
Opened 2024-07-11 06:26 UTC by ritik-bizbrolly

2024-07-11 11:06 UTC, drtechie commented on app/src/main/java/org/piramalswasthya/sakhi/configuration/Dataset.kt
> +
Indentation is off

2024-07-11 11:06 UTC, drtechie commented on app/src/main/java/org/piramalswasthya/sakhi/configuration/EligibleCoupleTrackingDataset.kt
> +//            isPregnant,
remove comments

2024-07-11 11:07 UTC, drtechie commented on app/src/main/java/org/piramalswasthya/sakhi/configuration/EligibleCoupleTrackingDataset.kt
> +                {
Follow same pattern with curly braces? Some places it's in new line, some places it's with the if condition.

2024-07-11 11:07 UTC, drtechie commented on app/src/main/java/org/piramalswasthya/sakhi/configuration/EligibleCoupleTrackingDataset.kt
> +                    Log.e("Positive","$index ${pregnancyTestResult.value}")
remove logs

2024-07-11 11:08 UTC, drtechie commented on app/src/main/java/org/piramalswasthya/sakhi/configuration/EligibleCoupleTrackingDataset.kt
> +
remove unnecessary line breaks and logs.

2024-07-11 11:08 UTC, drtechie commented on app/src/main/java/org/piramalswasthya/sakhi/configuration/PregnantWomanRegistrationDataset.kt
> +           /* val calendar = Calendar.getInstance()
logs and commented code to be removed.

2024-07-11 11:08 UTC, drtechie commented on app/src/main/java/org/piramalswasthya/sakhi/configuration/PregnantWomanRegistrationDataset.kt
> +        min=pwRegisterBeforeoneYear(),
space around =

2024-07-11 11:08 UTC, drtechie requested changes
Several clean code comments.

2024-07-11 11:09 UTC, drtechie commented
Add a description of what is addressed here.

2024-07-11 12:43 UTC, ritik-bizbrolly commented
Hello,

I have made the required changes and will follow the guidelines from here on.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mithun James ***@***.***>
Sent: Thursday, July 11, 2024 4:39:39 PM
To: PSMRI/FLW-Mobile-App ***@***.***>
Cc: Ritik ***@***.***>; Author ***@***.***>
Subject: Re: [PSMRI/FLW-Mobile-App] Eligible couple tracking bugs done (PR #4)


Add a description of what is addressed here.

—
Reply to this email directly, view it on GitHub<https://github.com/PSMRI/FLW-Mobile-App/pull/4#issuecomment-2222650964>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BJT7GX2B4AOOQ3WKIWIW7A3ZLZRXHAVCNFSM6AAAAABKWJFMZWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEMRSGY2TAOJWGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-16 06:19 UTC, sushant-bizbrolly reviewed
Changes are done.

2024-07-31 05:32 UTC, drtechie approved these changes

2024-07-31 13:02 UTC, merged