assamese language translation
PSMRI/FLW-Mobile-App pull request #8
Opened 2024-08-01 07:03 UTC by ritik-bizbrolly

Added translation for assamese languages.

2024-08-01 15:28 UTC, drtechie requested changes
There are conflcts in the PR.
Several files still show English instead of Assamese.

2024-08-02 05:26 UTC, drtechie commented on app/src/main/res/values-hi/strings_pwr.xml
@ritik-bizbrolly was referring to this one regarding English.

2024-08-02 05:49 UTC, drtechie commented on app/src/main/res/values-hi/strings_pwr.xml
This is under hi folder.
So should be Hindi right?

2024-08-02 06:12 UTC, sushant-bizbrolly commented on app/src/main/res/values-hi/strings_pwr.xml
These are Hindi translations, I asked Bala to add a ticket for Hindi translations. Will be working on it once everything is ready.

2024-08-02 06:14 UTC, sushant-bizbrolly commented
Conflicts will be resolved once we merge the code.

2024-08-13 06:44 UTC, merged